#!/bin/sh

sudo apt-get install git

git clone https://github.com/spring-guides/gs-rest-service.git

cd gs-rest-service/initial

git clone https://github.com/tubav/Monitoring_SE_Zabbix_RESTful_API.git

cp -r Monitoring_SE_Zabbix_RESTful_API/RESTful-API/build .
cp Monitoring_SE_Zabbix_RESTful_API/RESTful-API/build.gradle .
cp -r Monitoring_SE_Zabbix_RESTful_API/RESTful-API/src .

echo "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>" > properties.xml
echo "<!DOCTYPE properties SYSTEM \"http://java.sun.com/dtd/properties.dtd\">" >> properties.xml
echo "<properties>" >> properties.xml
echo "Please enter the IP of the monitoring server (Zabbix server): "
read server_ip
echo "    <entry key=\"server_ip\">$server_ip/zabbix</entry>" >> properties.xml
echo "</properties>" >> properties.xml

./gradlew bootRun &

